import Footer from "@/components/Footer";
import "../styles/switzer.css";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Sora } from "next/font/google";

export const metadata = {
  title: "AWCH",
  description: "Generated by create next app",
  icons: {
    icon: "/favIcon.png",
  },
};

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased ${sora.variable} bg-black-50`}>
        <Navbar />
        <main className="max-w-[1280px] mx-auto">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
