import Footer from "@/components/Footer";
import "../styles/switzer.css";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Sora } from "next/font/google";

export const metadata = {
  title: "Awch",
  description: "Generated by create next app",
};

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased ${sora.variable} `}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
